version: '3.3'
services:
  chrome:
    image: zenika/alpine-chrome:80
    container_name: chrome
    entrypoint: ["chromium-browser", "--headless", "--disable-gpu", "--disable-software-rasterizer", "--disable-dev-shm-usage", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    networks:
      - health-form-test
    
  healthform:
    image: healthform:test
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chrome
    networks:
      - health-form-test
    volumes:
      - ./screenshots:/usr/app/build/screenshots
    environment:
      BROWSER_URL: http://chrome:9222
    ports:
      - 5000:5000

networks:
  health-form-test:

